using System.ComponentModel;

namespace obs_cli.Enums
{
    public enum AvailableCommand
    {
        [Description("audio-input-magnitude")]
        AudioInputMagnitude,
        [Description("audio-output-magnitude")]
        AudioOutputMagnitude,
        [Description("cancel-recording")]
        CancelRecording,
        [Description("capture-mouse-click")]
        CaptureMouseClick,
        [Description("change-webcam")]
        ChangeWebcam,
        [Description("delete-last-section")]
        DeleteLastSection,
        [Description("disable-webcam")]
        DisableWebcam,
        [Description("disable-webcam-only")]
        DisableWebcamOnly,
        [Description("enable-webcam")]
        EnableWebcam,
        [Description("enable-webcam-only")]
        EnableWebcamOnly,
        [Description("exception-thrown")]
        ExceptionThrown,
        [Description("get-audio-input-devices")]
        GetAudioInputDevices,
        [Description("get-audio-magnitudes")]
        GetAudioMagnitudes,
        [Description("get-audio-output-devices")]
        GetAudioOutputDevices,
        [Description("get-webcam-devices")]
        GetWebcamDevices,
        [Description("get-webcam-window-properties")]
        GetWebcamWindowProperties,
        [Description("initialize")]
        Initialize,
        [Description("mouse-click-complete")]
        MouseClickComplete,
        [Description("move-webcam-window")]
        MoveWebcamWindow,
        [Description("pause-recording")]
        PauseRecording,
        [Description("position-webcam-window")]
        PositionWebcamWindow,
        [Description("resume-recording")]
        ResumeRecording,
        [Description("set-mouse-click-highlight-position")]
        SetMouseClickHighlightPosition,
        [Description("start-recording")]
        StartRecording,
        [Description("stop-recording")]
        StopRecording,
        [Description("terminate")]
        Terminate,
        [Description("toggle-full-screen")]
        ToggleFullScreen,
        [Description("update-audio-input-device")]
        UpdateAudioInputDevice,
        [Description("update-audio-output-device")]
        UpdateAudioOutputDevice,
        [Description("update-selection-window-position")]
        UpdateSelectionWindowPosition
    }
}
